### ISSUE TITLE
Exceeding 1024 Discord Character Limit + Rounding Tweak

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Bots/partner-bot#17]
## Emotes
If server has too many emotes, the advertisement message will be too big for discord to display as a message as it will exceed the 1024 character limit.

https://github.com/Valks-Bots/partner-bot/blob/b43ad95e7f6a20dc471992b9b7301529dbe03a06/src/commands/partner/bump.js#L106-L110

Fix: Add conditional here. "If emotes > some number then only display first x, otherwise display all emotes"

## Rounding
Following code displays ALL the decimals, could be rounded with Math.round()
https://github.com/Valks-Bots/partner-bot/blob/b43ad95e7f6a20dc471992b9b7301529dbe03a06/src/commands/partner/bump.js#L103

**Comment by sayantan300** [comment]
Is it fixed?

**Comment by valkyrienyanko** [comment]
> Is it fixed?

No, haven't had the time.

**Comment by sayantan300** [comment]
I think it's better to remove the "emojis" part, since the other partnership bots don't have that thing and that's the only problem ...

Contact me : Progamer 😎#3286
Guild: https://discord.gg/Rf3xPMm

Looking forward to talk with you

**Comment by Experilux** [comment]
Hello, How do I fix this issue?

**Comment by Experilux** [comment]
it is giving the error even without emojis, it is only working for 1 server.

**Comment by valkyrienyanko** [comment]
> it is giving the error even without emojis, it is only working for 1 server.

The only thing I can think of that would cause this is the server description character limit was removed and was passed and thus too many characters being displayed in one Discord message.

**Comment by valkyrienyanko** [comment]
I won't be able to fix this anytime soon, so anyone is welcome to open a PR.
