### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Experilux** [Valks-Bots/partner-bot#19]
When I try to bump a server, it is giving me an error. The ad has no emojis,links, or anything like that and is very short. How can I fix this?

**Comment by Experilux** [comment]
Only 1 server will bump, the others wont. The only It does not give me an error is just on 1 server.

**Comment by valkyrienyanko** [comment]
Showing the error message could be useful.

**Comment by valkyrienyanko** [comment]
Possible duplicate of #17
