### ISSUE TITLE
help not working

### ISSUE THREAD

**Issue by F1R3L1GHT** [Valks-Bots/partner-bot#28]
(node:80888) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tag' of undefined
    at Object.exports.run (/Users/juantan/Downloads/part/src/commands/utility/help.js:16:84)
    at /Users/juantan/Downloads/part/src/events/message.js:40:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:80888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by valkyrienyanko** [comment]
You need to define `client.config.ownerID` in the config to be your owner ID.
