### ISSUE TITLE
Sending Twice

### ISSUE THREAD

**Issue by SadafYurei** [Valks-Bots/partner-bot#31]
whenever i do t!help. or any command, sends the message twice

**Comment by valkyrienyanko** [comment]
Perhaps there are two instances of the bot running at the same time causing it to send a message from each instance when you execute any command.

**Comment by SadafYurei** [comment]
Yeah it was, my bad.. Also with the bump command the cooldown starts even if the users don't have a channel setup, or a description, if they don't have either of those the bump cooldown still goes through even if they didn't bump, you know how to fix that issue?

**Comment by valkyrienyanko** [comment]
I will look at this when I have the time. Thanks for pointing it out.

**Comment by SadafYurei** [comment]
you are welcome :), respond if you know how to fix this problem.

**Comment by valkyrienyanko** [comment]
> Yeah it was, my bad.. Also with the bump command the cooldown starts even if the users don't have a channel setup, or a description, if they don't have either of those the bump cooldown still goes through even if they didn't bump, you know how to fix that issue?

If you're still having this problem, open up a new issue. I'm closing this current issue as the sending twice issue seems to just be because you had 2 bots going at the same time.
