### ISSUE TITLE
Add Heroku Guide

### ISSUE THREAD

**Issue by lordm121** [Valks-Bots/partner-bot#34]
Please tell me how to can I host on heroku

**Comment by hama120** [comment]
I hosted by heroku 😎

**Comment by valkyrienyanko** [comment]
Would you be willing to add a step by step guide so others know how to host by Heroku as well?

**Comment by vghcodesjs** [comment]
Just watch this video: https://www.youtube.com/watch?v=8qIsRzV0Hpg

**Comment by vghcodesjs** [comment]
> Would you be willing to add a step by step guide so others know how to host by Heroku as well?

Just watch this video: https://www.youtube.com/watch?v=8qIsRzV0Hpg

**Comment by lordm121** [comment]
Valkyrienyanko 
Ok I tell you setp by step but first tell me why after 1 day bot want init channel when I setup channel before

**Comment by valkyrienyanko** [comment]
> Valkyrienyanko
> Ok I tell you setp by step but first tell me why after 1 day bot want init channel when I setup channel before

Heroku resets the database every 24 hours. You're better off finding a paid host or hosting the bot on your local machine.

Someone added a Heroku guide to the README.md
